file.input: car-list.csv
---
server:
  port: 8080
  # H2 Database
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  datasource2:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root    
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  main:
    allow-bean-definition-overriding: true    